
DROP TABLE roles IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE companies IF EXISTS;

CREATE TABLE companies (
    id             INTEGER      GENERATED BY DEFAULT AS IDENTITY
                                (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
    name           VARCHAR(250) NOT NULL,
    active         BOOLEAN      DEFAULT TRUE NOT NULL,

    CONSTRAINT unique_company_name UNIQUE (name)
);

CREATE TABLE users (
    id             INTEGER      GENERATED BY DEFAULT AS IDENTITY
                                (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
    login          VARCHAR(32)  NOT NULL,
    hashed_pass    VARCHAR(128) NOT NULL,
    email          VARCHAR_IGNORECASE(255) NOT NULL,
    first_name     VARCHAR(50)  NOT NULL,
    last_name      VARCHAR(50)  NOT NULL,
    active         BOOLEAN      DEFAULT TRUE NOT NULL,

    CONSTRAINT unique_user_login UNIQUE (login),
    CONSTRAINT unique_user_email UNIQUE (email)
);

CREATE TABLE roles (
    name           VARCHAR(30)  NOT NULL,
    user_id        INTEGER      NOT NULL,
    
    CONSTRAINT unique_role UNIQUE (name, user_id),

    CONSTRAINT fk_roles_user_id FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

